'use strict';
const PATHS={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',calendar:'M8 2v4 M16 2v4 M3 10h18 M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2',chart:'M3 3v18h18 M7 14l4-5 4 3 6-8',clock:'M12 8v4l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',layers:'m12 3 10 5-10 5L2 8z M2 12l10 5 10-5 M2 16l10 5 10-5',new:'M12 3v18 M3 12h18',external:'M14 3h7v7 M21 3l-9 9 M10 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${PATHS[n]||PATHS.grid}"/></svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nf=new Intl.NumberFormat('zh-CN');const fmt=n=>nf.format(n);const wan=n=>(n/10000).toFixed(1)+'万';
const color=id=>`var(--color-chart-${id})`;
let archive={days:[]},state={date:'',board:'hot',view:'daily',query:'',onlyNew:false,trendQuery:'',trendWindow:30};
const $=s=>document.querySelector(s);const day=()=>archive.days.find(d=>d.date===state.date);const previous=()=>archive.days.filter(d=>d.date<state.date).at(-1);
const allEntries=d=>d.boards.flatMap(b=>b.entries.map(e=>({...e,boardId:b.id,boardName:b.name,source:b.source})));
const unique=d=>new Set(allEntries(d).map(e=>e.title));
const currentBoard=()=>day().boards.find(b=>b.id===state.board);
const prevBoard=()=>previous()?.boards.find(b=>b.id===state.board);
const hasBoardBaseline=()=>Boolean(prevBoard()?.entries.length);
const trendDays=()=>archive.days.filter(d=>d.date<=state.date&&(!state.trendWindow||Date.parse(d.date+'T00:00:00Z')>=Date.parse(state.date+'T00:00:00Z')-(state.trendWindow-1)*86400000));
const trendBoards=()=>[...new Map(trendDays().flatMap(d=>d.boards).map(b=>[b.id,{id:b.id,name:b.name}])).values()];
function comparableTopics(d,p){
 const ids=new Set(d.boards.filter(b=>b.entries.length&&p?.boards.some(old=>old.id===b.id&&old.entries.length)).map(b=>b.id));
 if(!ids.size)return {fresh:'—',count:0};
 const titles=report=>new Set(report.boards.filter(b=>ids.has(b.id)).flatMap(b=>b.entries.map(e=>e.title)));
 const current=titles(d),old=titles(p);
 return {fresh:[...current].filter(title=>!old.has(title)).length,count:ids.size};
}
function dateLabel(d){return d.replaceAll('-','.');}
function collected(d){const s=d.collectedAt;return s.includes('T')?s.slice(11,19):s.match(/\d{2}:\d{2}:\d{2}/)?.[0]||'时间未记录';}
function change(e){if(!hasBoardBaseline())return '<span class="change same">—</span>';const p=prevBoard()?.entries.find(x=>x.title===e.title);if(!p)return '<span class="change new">新上榜</span>';const delta=p.rank-e.rank;return delta===0?'<span class="change same">持平</span>':`<span class="change ${delta>0?'up':'down'}">${delta>0?'↑':'↓'} ${Math.abs(delta)}</span>`;}
function stat(label,value,unit,note,ico,positive=false){return `<div class="stat"><div class="stat-label">${label}${icon(ico)}</div><div class="stat-value">${value}<small>${unit}</small></div><p class="stat-note ${positive?'note-positive':''}">${note}</p></div>`;}
function stats(){
 const d=day(),p=previous(),u=unique(d),comparison=comparableTopics(d,p);
 const note=comparison.count?`与 ${p.date.slice(5).replace('-','月')} 日同口径比较 · ${comparison.count} 榜 · 标题去重`:p?'暂无共同有数据的榜单':'首份日报，暂无对比基准';
 return `<section class="stats" aria-label="日报概况">${stat('收录条目',allEntries(d).length,'条',`${d.boards.length} 份榜单 · ${u.size} 个独立话题`,'layers')}${stat('同口径新话题',comparison.fresh,'个',note,'new',!!comparison.count)}${stat('覆盖榜单',d.boards.length,'榜','每榜保留原始前 20 名','chart')}${stat('已归档',archive.days.length,'天',`${archive.days[0].date.slice(5).replace('-','/')} 起持续记录`,'calendar')}</section>`;
}
function chartBars(){
 const rows=day().boards.map(b=>({...b,average:b.entries.length?b.entries.reduce((s,e)=>s+e.heat,0)/b.entries.length:null}));
 const max=Math.max(...rows.filter(b=>b.average!==null).map(b=>b.average),1);
 return rows.map(b=>`<div class="bar-row" style="--board-color:${color(b.id)}"><div class="bar-top"><span class="bar-name"><i class="board-dot"></i>${esc(b.name)}</span><span class="bar-value">${b.average===null?'暂无数据':wan(b.average)}</span></div>${b.average===null?'':`<div class="bar-track" role="img" aria-label="${esc(b.name)}平均热度${Math.round(b.average)}"><div class="bar-fill" style="width:${b.average/max*100}%"></div></div>`}</div>`).join('');
}
function repeatTopics(){const groups=new Map();for(const e of allEntries(day())){if(!groups.has(e.title))groups.set(e.title,[]);groups.get(e.title).push(e);}return [...groups].filter(([,es])=>es.length>1).sort((a,b)=>b[1].length-a[1].length||Math.max(...b[1].map(e=>e.heat))-Math.max(...a[1].map(e=>e.heat)));}
function renderDaily(){const d=day(),b=currentBoard();if(!hasBoardBaseline())state.onlyNew=false;$('#app').innerHTML=(d.warnings?.length?`<div class="data-warning" role="status"><strong>本份日报的数据说明</strong>${d.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}</div>`:'')+stats()+`<div class="main-grid"><section class="panel"><div class="panel-title"><div><h2>${d.boards.length} 榜速览</h2><p>保留原榜排名，记录每个热点的变化</p></div><span class="mini-label">TOP 20</span></div><div class="board-tabs" role="tablist" aria-label="选择榜单">${d.boards.map(x=>`<button role="tab" aria-selected="${x.id===state.board}" class="board-tab ${x.id===state.board?'active':''}" data-board="${x.id}">${x.name}</button>`).join('')}</div><div class="list-tools"><label class="searchbox">${icon('search')}<span class="sr-only">搜索当前榜单</span><input id="topic-search" placeholder="搜索榜单中的话题…" value="${esc(state.query)}"><kbd>⌘ K</kbd></label><button class="filter-button ${state.onlyNew?'active':''}" id="only-new" aria-pressed="${state.onlyNew}" ${!hasBoardBaseline()?'disabled title="上一份日报没有同榜数据，暂无对比基准"':''}>只看新上榜</button></div><div id="rank-results"></div><div class="table-footer"><span>榜单更新 ${esc(b.updatedAt.slice(11,19)||'未取得')} · 采集 ${collected(d)}</span><a href="${esc(b.source)}" target="_blank" rel="noopener noreferrer">官方来源</a></div></section><aside class="side-stack"><section class="panel"><div class="panel-title"><div><h2>${d.boards.length} 榜热度分布</h2><p>各榜前20名的平均热度</p></div></div><div class="board-bars">${chartBars()}</div><p class="panel-footnote">热度为官方榜单值，不代表播放量。</p></section><section class="panel"><div class="panel-title"><h2>跨榜热议</h2><span class="mini-label">${repeatTopics().length} 个话题</span></div><div class="repeat-list">${repeatTopics().slice(0,4).map(([title,es])=>`<div class="repeat-item"><button data-topic="${esc(title)}">${esc(title)}</button><div class="repeat-meta"><span class="mini-tag">${es.length} 榜共现</span>${es.map(e=>e.boardName.slice(0,-1)).join(' · ')}</div></div>`).join('')||'<p class="empty-state">这一天暂无跨榜话题</p>'}</div></section><section class="insight-note"><h3>让热点有迹可循</h3><p>选择标题可查看已归档日期中的排名与热度。“新上榜”仅表示未出现在上一份同榜前20名中；缺少同榜基准时显示“—”。新话题仅比较两份日报均有数据的榜单。</p></section></aside></div>`;renderRows();}
function renderRows(){const b=currentBoard(),p=prevBoard();let rows=b.entries.filter(e=>e.title.toLowerCase().includes(state.query.toLowerCase()));if(state.onlyNew&&hasBoardBaseline())rows=rows.filter(e=>!p?.entries.some(x=>x.title===e.title));if(!rows.length){$('#rank-results').innerHTML=`<div class="empty-state"><strong>没有匹配的话题</strong>试试其他关键词，或清除筛选。<br><button class="secondary-button" id="clear-search">清除筛选</button></div>`;return;}const max=Math.max(...b.entries.map(e=>e.heat));$('#rank-results').innerHTML=`<table class="rank-table"><thead><tr><th scope="col">排名</th><th scope="col">热点话题</th><th scope="col">热度值</th><th scope="col">变化</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${String(e.rank).padStart(2,'0')}</td><td><button class="topic-button" data-topic="${esc(e.title)}">${esc(e.title)}</button></td><td class="heat-cell">${fmt(e.heat)}<span class="heat-track" aria-hidden="true"><i style="width:${e.heat/max*100}%"></i></span></td><td class="change-cell">${change(e)}</td></tr>`).join('')}</tbody></table>`;}
function render(){const d=day();
 if(!d.boards.some(b=>b.id===state.board)){state.board=d.boards.some(b=>b.id==='hot')?'hot':d.boards[0]?.id;state.onlyNew=false;}
 if(!hasBoardBaseline())state.onlyNew=false;
 $('#board-nav').innerHTML=d.boards.map(b=>`<button data-board="${esc(b.id)}" style="--board-color:${color(b.id)}" aria-current="${b.id===state.board?'true':'false'}"><i class="board-dot"></i>${esc(b.name)}</button>`).join('');
 $('#board-nav-label').textContent=`${d.boards.length} 份榜单`;
 const labels={daily:'每日概览',archive:'历史归档',trends:'热词追踪',opportunities:'商品机会'};$('#breadcrumb-current').textContent=labels[state.view];document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===state.view));$('#heading-date').textContent=d.date+' · '+new Intl.DateTimeFormat('zh-CN',{weekday:'long',timeZone:'Asia/Shanghai'}).format(new Date(d.date+'T12:00:00+08:00'));$('#page-title').textContent=state.view==='daily'?'今天的热度，都在这里。':state.view==='archive'?'每一份日报，都是积累。':state.view==='opportunities'?'从热点，找到下一件可卖的商品。':'找到下一条值得跟进的话题。';$('#subtitle').textContent=state.view==='daily'?`${d.boards.length} 榜 ${allEntries(d).length} 条 · 实际采集于北京时间 ${collected(d)}`:state.view==='archive'?`已收录 ${archive.days.length} 天，${archive.days.reduce((n,d)=>n+allEntries(d).length,0)} 条榜单记录。`:state.view==='opportunities'?'从原料、模具到包装，先核实需求，再决定进货。':'从榜单后段的升温线索，到每个话题的完整轨迹。';$('#date-select').value=state.date;if(state.view==='daily')renderDaily();else if(state.view==='archive')renderArchive();else if(state.view==='opportunities')OpportunitiesView.render();else renderTrends();}
function renderArchive(){
 $('#app').innerHTML=`<div class="archive-grid">${[...archive.days].reverse().map(d=>`<article class="panel archive-card"><div class="archive-top"><div class="calendar-tile"><span>${Number(d.date.slice(5,7))}月</span><strong>${d.date.slice(8)}</strong></div><div><h2>${d.date} 日报</h2><p>${d.boards.length} 榜 · ${allEntries(d).length} 条记录 · ${unique(d).size} 个话题</p></div></div>${d.boards.map(b=>`<div class="archive-board"><span>${b.name}</span><p>${esc(b.entries[0]?.title||'暂无数据')}</p></div>`).join('')}<div class="archive-actions"><span>采集于 ${collected(d)}</span><button class="secondary-button" data-date="${d.date}">查看日报</button></div></article>`).join('')}</div><p class="notice">归档保留实际采集时间。${archive.days.length<7?'当前仅有 '+archive.days.length+' 天数据，后续日报将持续累积。':''}</p>`;
}
function trendChart(){
 const days=trendDays(),width=Math.min(860,Math.max(250,innerWidth-(innerWidth<640?84:innerWidth<960?110:460))),height=265,left=58,right=24,top=24,bottom=40;const values=days.flatMap(d=>d.boards.filter(b=>b.entries.length).map(b=>b.entries.reduce((s,e)=>s+e.heat,0)/b.entries.length));
 const max=Math.ceil(Math.max(...values,1)/2000000)*2000000;const dates=days.map(d=>Date.parse(d.date+'T00:00:00Z'));const span=Math.max(dates.at(-1)-dates[0],86400000);const x=i=>left+(dates[i]-dates[0])*(width-left-right)/span;const y=v=>height-bottom-v/max*(height-top-bottom);
 let out=`<svg class="trend-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="已归档日期各榜前20名的平均热度趋势，纵轴从零开始">`;
 for(let i=0;i<=4;i++){const v=max*i/4;out+=`<line class="gridline" x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}"/><text x="${left-12}" y="${y(v)+4}" text-anchor="end">${v/10000}万</text>`;}
 days.forEach((d,i)=>{if(days.length<=7||i===0||i===days.length-1||i%Math.ceil(days.length/6)===0)out+=`<text x="${x(i)}" y="${height-10}" text-anchor="middle">${d.date.slice(5).replace('-','/')}</text>`;});
 for(const b of trendBoards()){const pts=days.map((d,i)=>{const board=d.boards.find(e=>e.id===b.id);return board?.entries.length?{i,d,v:board.entries.reduce((s,e)=>s+e.heat,0)/board.entries.length}:null;});let path='',lastPoint=null;for(const p of pts){if(!p){lastPoint=null;continue;}const connected=lastPoint&&dates[p.i]-dates[lastPoint.i]===86400000;path+=(connected?' L':' M')+x(p.i)+','+y(p.v);lastPoint=p;}out+=`<g style="--board-color:${color(b.id)}"><path class="line" d="${path}"/>${pts.filter(Boolean).map(p=>`<circle class="point" cx="${x(p.i)}" cy="${y(p.v)}" r="4"><title>${p.d.date} ${b.name} 平均热度 ${fmt(Math.round(p.v))}</title></circle>`).join('')}</g>`;}
 return out+'</svg>';
}
function renderTrends(){TrackingView.render();}
function renderTrendRows(){TrackingView.rows(true);}
function openTopic(title,board){TrackingView.open(title,board);}
function downloadReport(){const d=day();let text=`# 抖音热榜每日日报｜${d.date}\n\n实际采集：${d.collectedAt}（北京时间）\n\n`;if(d.warnings?.length)text+='## 数据说明\n\n'+d.warnings.map(w=>'- '+String(w)).join('\n')+'\n\n';for(const b of d.boards){text+=`## ${b.name}\n\n榜单更新：${b.updatedAt}\n\n[官方来源](${b.source})\n\n| 原榜排名 | 标题 | 热度值 |\n| ---: | --- | ---: |\n`;for(const e of b.entries)text+=`| ${e.rank} | ${e.title.replaceAll('|','\\|')} | ${fmt(e.heat)} |\n`;text+='\n';}const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`抖音热榜每日日报-${d.date}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view){state.view=view.dataset.view;history.replaceState(null,'','#'+state.view);render();}if(e.target.closest('.brand')){e.preventDefault();state.view='daily';render();}const board=e.target.closest('[data-board]');if(board){state.board=board.dataset.board;state.view='daily';state.query='';state.onlyNew=false;render();}const topic=e.target.closest('[data-topic]');if(topic)openTopic(topic.dataset.topic,topic.dataset.topicBoard);if(e.target.closest('#only-new')&&hasBoardBaseline()){state.onlyNew=!state.onlyNew;renderDaily();}if(e.target.closest('#clear-search')){state.query='';state.onlyNew=false;renderDaily();}const d=e.target.closest('[data-date]');if(d){state.date=d.dataset.date;state.view='daily';state.query='';state.onlyNew=false;render();window.scrollTo({top:0});}});
document.addEventListener('input',e=>{if(e.target.id==='topic-search'){state.query=e.target.value;renderRows();}if(e.target.id==='trend-search'){state.trendQuery=e.target.value;renderTrendRows();}});
$('#date-select').addEventListener('change',e=>{state.date=e.target.value;state.query='';state.onlyNew=false;render();});$('#export-button').addEventListener('click',downloadReport);$('#topic-dialog').addEventListener('click',e=>{if(e.target===$('#topic-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(state.view!=='daily'){state.view='daily';render();}$('#topic-search')?.focus();}});
document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
fetch('archive.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error('归档读取失败');return r.json();}).then(data=>{if(!Array.isArray(data.days)||!data.days.length)throw new Error('暂无日报');archive=data;archive.days.sort((a,b)=>a.date.localeCompare(b.date));state.date=archive.days.at(-1).date;const initialView=location.hash.slice(1);if(['daily','archive','trends','opportunities'].includes(initialView))state.view=initialView;$('#date-select').innerHTML=[...archive.days].reverse().map(d=>`<option value="${d.date}">${dateLabel(d.date)}</option>`).join('');$('#archive-count').textContent=archive.days.length;$('#coverage').textContent=`已记录 ${archive.days.length} 天`;render();}).catch(()=>{$('#app').innerHTML='<div class="empty-state"><strong>日报暂时无法读取</strong>请刷新页面重试；若持续失败，请回到日报任务检查归档更新。<br><button class="secondary-button" onclick="location.reload()">重新读取</button></div>';$('#export-button').disabled=true;});

let lastChartWidth=innerWidth;window.addEventListener("resize",()=>{if(innerWidth!==lastChartWidth){lastChartWidth=innerWidth;if(state.view==="trends"&&archive.days.length)renderTrends();}});

window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(archive.days.length&&['daily','archive','trends','opportunities'].includes(view)){state.view=view;render();}});
